services:
  db:
    image: postgres:13
    container_name: database
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:4200"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
    networks:
      - app-network
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge